//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protobuf/wrp-example.proto

package pbkit.wrp.example;

@kotlin.jvm.JvmSynthetic
public inline fun getSliderValueResponse(block: pbkit.wrp.example.GetSliderValueResponseKt.Dsl.() -> kotlin.Unit): pbkit.wrp.example.WrpExample.GetSliderValueResponse =
  pbkit.wrp.example.GetSliderValueResponseKt.Dsl._create(pbkit.wrp.example.WrpExample.GetSliderValueResponse.newBuilder()).apply { block() }._build()
public object GetSliderValueResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pbkit.wrp.example.WrpExample.GetSliderValueResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pbkit.wrp.example.WrpExample.GetSliderValueResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pbkit.wrp.example.WrpExample.GetSliderValueResponse = _builder.build()

    /**
     * <code>int32 value = 1;</code>
     */
    public var value: kotlin.Int
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * <code>int32 value = 1;</code>
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pbkit.wrp.example.WrpExample.GetSliderValueResponse.copy(block: pbkit.wrp.example.GetSliderValueResponseKt.Dsl.() -> kotlin.Unit): pbkit.wrp.example.WrpExample.GetSliderValueResponse =
  pbkit.wrp.example.GetSliderValueResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
