//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protobuf/wrp-example.proto

package pbkit.wrp.example;

@kotlin.jvm.JvmSynthetic
public inline fun getSliderValueRequest(block: pbkit.wrp.example.GetSliderValueRequestKt.Dsl.() -> kotlin.Unit): pbkit.wrp.example.WrpExample.GetSliderValueRequest =
  pbkit.wrp.example.GetSliderValueRequestKt.Dsl._create(pbkit.wrp.example.WrpExample.GetSliderValueRequest.newBuilder()).apply { block() }._build()
public object GetSliderValueRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pbkit.wrp.example.WrpExample.GetSliderValueRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pbkit.wrp.example.WrpExample.GetSliderValueRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pbkit.wrp.example.WrpExample.GetSliderValueRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pbkit.wrp.example.WrpExample.GetSliderValueRequest.copy(block: pbkit.wrp.example.GetSliderValueRequestKt.Dsl.() -> kotlin.Unit): pbkit.wrp.example.WrpExample.GetSliderValueRequest =
  pbkit.wrp.example.GetSliderValueRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
