//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protobuf/wrp-example.proto

package pbkit.wrp.example;

@kotlin.jvm.JvmSynthetic
public inline fun getTextValueRequest(block: pbkit.wrp.example.GetTextValueRequestKt.Dsl.() -> kotlin.Unit): pbkit.wrp.example.WrpExample.GetTextValueRequest =
  pbkit.wrp.example.GetTextValueRequestKt.Dsl._create(pbkit.wrp.example.WrpExample.GetTextValueRequest.newBuilder()).apply { block() }._build()
public object GetTextValueRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pbkit.wrp.example.WrpExample.GetTextValueRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pbkit.wrp.example.WrpExample.GetTextValueRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pbkit.wrp.example.WrpExample.GetTextValueRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pbkit.wrp.example.WrpExample.GetTextValueRequest.copy(block: pbkit.wrp.example.GetTextValueRequestKt.Dsl.() -> kotlin.Unit): pbkit.wrp.example.WrpExample.GetTextValueRequest =
  pbkit.wrp.example.GetTextValueRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
