//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protobuf/wrp-example.proto

package pbkit.wrp.example;

@kotlin.jvm.JvmSynthetic
public inline fun getTextValueResponse(block: pbkit.wrp.example.GetTextValueResponseKt.Dsl.() -> kotlin.Unit): pbkit.wrp.example.WrpExample.GetTextValueResponse =
  pbkit.wrp.example.GetTextValueResponseKt.Dsl._create(pbkit.wrp.example.WrpExample.GetTextValueResponse.newBuilder()).apply { block() }._build()
public object GetTextValueResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pbkit.wrp.example.WrpExample.GetTextValueResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pbkit.wrp.example.WrpExample.GetTextValueResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pbkit.wrp.example.WrpExample.GetTextValueResponse = _builder.build()

    /**
     * <code>string text = 1;</code>
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.getText()
      @JvmName("setText")
      set(value) {
        _builder.setText(value)
      }
    /**
     * <code>string text = 1;</code>
     */
    public fun clearText() {
      _builder.clearText()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pbkit.wrp.example.WrpExample.GetTextValueResponse.copy(block: pbkit.wrp.example.GetTextValueResponseKt.Dsl.() -> kotlin.Unit): pbkit.wrp.example.WrpExample.GetTextValueResponse =
  pbkit.wrp.example.GetTextValueResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
